export const putEmail = 'Enter an email'
export const putValidEmail= 'Enter a valid email'
export const putPassword = 'Enter a password'
export const putValidPassword = 'Tha password must have at least 6 characters'
export const userOk = 'Invalid user'
export const userNotOk = 'Unregistered user'
export const userDeleted = 'Deleted user'
export const error = 'ERROR'
export const dontHaveACount = 'You do not have an account?'
export const alreadyHaveACount = 'Do you already have an account?'
export const wrongPassword = 'The password is invalid or the user does not have a password'
export const user = 'User'
export const password = 'Password'
export const confirmPassword = 'Confirm password'
export const email = 'Email'
export const enter = 'ENTER'
export const registerButton = 'REGISTER'
export const register = 'Register'
export const userCreated = 'User created'
export const userAlreadyInUse = 'User already exits in Firebase'
export const userNotCreated = 'User does not exits in Firebase'
export const equalsPasswords = 'Both passwords must be equals'
export const beginSession = 'log in'

//MENU
export const logout = 'LOGOUT'